language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install python-coveralls
  - pip install pytest-cov
script:
  - pytest --cov=bestPlace/
after_success: 
- coverage report
- coveralls
